# '*************************'
#  List visitor forecasts to plot ----
# '*************************'

hi  <-  c("VIS_HI", "VISUS_HI", "VISJP_HI", "VISRES_HI", "VLOSUS_HI", "VLOSJP_HI", "VLOSRES_HI", "VLOS_HI", "VADCUS_HI", "VADCJP_HI", "VADCRES_HI", "VADC_HI", "TRMSADJ_HI", "OCUPPADJ_HI", "PPRM_HI", "PRM_HI", "VEXP_HI", "VEXP_R_HI", "VISCRAIR_HI", "VLOSCRAIR_HI")

# CNTY VIS LISTS ----
mau  <-  c("VIS_MAU","VISUS_MAU", "VISJP_MAU",  "VISRES_MAU", "VLOSUS_MAU", "VLOSJP_MAU", "VLOSRES_MAU", "VLOS_MAU", "VADCUS_MAU", "VADCJP_MAU", "VADCRES_MAU", "VADC_MAU", "TRMSADJ_MAU", "OCUPPADJ_MAU", "PPRM_MAU", "PRM_MAU")
hon  <-  c("VIS_HON",  "VISUS_HON",  "VISJP_HON",  "VISRES_HON", "VLOSUS_HON", "VLOSJP_HON", "VLOSRES_HON", "VLOS_HON", "VADCUS_HON", "VADCJP_HON", "VADCRES_HON", "VADC_HON", "TRMSADJ_HON", "OCUPPADJ_HON", "PPRM_HON")
haw  <-  c("VIS_HAW",  "VISUS_HAW",  "VISJP_HAW",  "VISRES_HAW", "VLOSUS_HAW", "VLOSJP_HAW", "VLOSRES_HAW", "VLOS_HAW", "VADCUS_HAW", "VADCJP_HAW", "VADCRES_HAW", "VADC_HAW", "TRMSADJ_HAW", "OCUPPADJ_HAW", "PPRM_HAW")
kau  <-  c("VIS_KAU",  "VISUS_KAU",  "VISJP_KAU",  "VISRES_KAU", "VLOSUS_KAU", "VLOSJP_KAU", "VLOSRES_KAU", "VLOS_KAU", "VADCUS_KAU", "VADCJP_KAU", "VADCRES_KAU", "VADC_KAU", "TRMSADJ_KAU", "OCUPPADJ_KAU", "PPRM_KAU")
all <- c(hi,hon, haw, kau, mau)

mauhead  <-  c("VIS_MAU", "VLOS_MAU", "VADC_MAU", "TRMSADJ_MAU", "OCUPPADJ_MAU", "PPRM_MAU")

# SHARE LISTS ----
honsh  <-  c("VIS_HON", "SH_US_HON", "VISUS_HON", "SH_JP_HON", "VISJP_HON", "SH_RES_HON", "VISRES_HON")
hawsh  <-  c("VIS_HAW", "SH_US_HAW", "VISUS_HAW", "SH_JP_HAW", "VISJP_HAW", "SH_RES_HAW", "VISRES_HAW")
kaush  <-  c("VIS_KAU", "SH_US_KAU", "VISUS_KAU", "SH_JP_KAU", "VISJP_KAU", "SH_RES_KAU", "VISRES_KAU")
maush  <-  c("VIS_MAU", "SH_US_MAU", "VISUS_MAU", "SH_JP_MAU", "VISJP_MAU", "SH_RES_MAU", "VISRES_MAU")
hish  <-  c("VIS_HI", "SH_US_HI", "VISUS_HI", "SH_JP_HI", "VISJP_HI", "SH_RES_HI", "VISRES_HI")

# US VIS LISTS ----
us <- c("VISUS_HI", "SH_US_HON", "VISUS_HON", "SH_US_HAW", "VISUS_HAW","SH_US_MAU", "VISUS_MAU", "SH_US_KAU", "VISUS_KAU")

# JP VIS LISTS ----
jp <- c("VISJP_HI", "SH_JP_HON", "VISJP_HON", "SH_JP_HAW", "VISJP_HAW","SH_JP_MAU", "VISJP_MAU", "SH_JP_KAU", "VISJP_KAU")

# RES VIS LISTS ----
res <- c("VISRES_HI", "SH_RES_HON", "VISRES_HON", "SH_RES_HAW", "VISRES_HAW","SH_RES_MAU", "VISRES_MAU", "SH_RES_KAU", "VISRES_KAU")



# LOS LISTS ----
vlos <- c("VLOS_HON", "VLOS_HAW", "VLOS_MAU", "VLOS_KAU", "VLOS_HI")
vlosjp <- c("VLOSJP_HON", "VLOSJP_HAW", "VLOSJP_MAU", "VLOSJP_KAU", "VLOSJP_HI")
vlosus <- c("VLOSUS_HAW", "VLOSUS_MAU", "VLOSUS_KAU", "VLOSUS_HI","VLOSUS_HON")
vlosres <- c("VLOSRES_HAW", "VLOSRES_MAU", "VLOSRES_KAU", "VLOSRES_HI","VLOSRES_HON")

# DAYs LISTS ----
vdayjp <- c("VDAYJP_HON", "VDAYJP_HAW", "VDAYJP_MAU", "VDAYJP_KAU")
vdayus <- c("VDAYUS_HON", "VDAYUS_HAW", "VDAYUS_MAU", "VDAYUS_KAU")
vdayres <- c("VDAYRES_HON", "VDAYRES_HAW", "VDAYRES_MAU", "VDAYRES_KAU")

# VADC LISTS ----
vadc_head <- c("VADC_HI","VADC_HON","VADC_NBI","VADC_HAW","VADC_KAU","VADC_MAU")
vadcjp <- c("VADCJP_HON", "VADCJP_HAW", "VADCJP_MAU", "VADCJP_KAU")
vadcus <- c("VADCUS_HON", "VADCUS_HAW", "VADCUS_MAU", "VADCUS_KAU")
vadcres <- c("VADCRES_HON", "VADCRES_HAW", "VADCRES_MAU", "VADCRES_KAU")
vadc_all <- c(vadcus,vadcjp,vadcres)

# TRMS LISTS ----
trms <- c("TRMSADJ_HI","TRMSADJ_HAW","TRMSADJ_MAU","TRMSADJ_HON","TRMSADJ_KAU")

ocupp <- c("OCUPPADJ_HAW", "OCUPPADJ_MAU", "OCUPPADJ_KAU", "OCUPPADJ_HI","OCUPPADJ_HON")

vexp <- c("VEXP_HI", "VEXP_RB_HI", "VADC_HI", "PRM_HI")

plot_list <- c(hi)
plot_list <- c(all)