vintages:
  prev: "25Q1"
  curr: "25Q2"

paths:
  raw: "data/raw"
  processed: "data/processed"
  equations: "equations"
  extend_script: "R/extend_qmain_history.R"
  wrangl_script: "R/wrangle_data.R"
  impext_script: "R/import_existing_fcst.R"
  # addfac_script: "R/add_qmod_25Q4.txt"
  addfac_script: "R/add_qmod.R" # blank add-factor file
  output: "output"
  figures: "output/figures"
  toursol_plot_list: "R/toursol_plot_list.R"
  qsol_plot_list: "R/qsol_plot_list.R"

constants:
  bank_start: 1970.1
  bank_end: 2100.4

data_qmain:
  data_from_disk: true
  exp_id_q: 333
  extend_history: false
  indicators_file: indicators.RDS
  save_output: true

combine_equations:
  eq_subset:
    - _eq.txt # this keeps all equations (or comment this and uncomment below)
    # - af                    
    # - ag                    
    # - cpi                   
    # - ct                    
    # - e_headline_identitites
    # - else                  
    # - fir                   
    # - gdp_r_res             
    # - gv                    
    # - gvfd                  
    # - gvml                  
    # - gvsl                  
    # - hc                    
    # - kp                    
    # - lf                    
    # - mn                    
    # - model                 
    # - nr                    
    # - ocup                  
    # - pafsgf_hon            
    # - pmkb                  
    # - pprm                  
    # - prm                   
    # - rates                 
    # - taxes                 
    # - trade                 
    # - trmsadj               
    # - tu                    
    # - vday_vadc             
    # - vexp                  
    # - vis                   
    # - visjp                 
    # - visres                
    # - visus                 
    # - vlos                  
    # - y_headline_identitites
    # - ymedc_hon   
    # - qmod # this is the translated AREMOS model
  save_output: true

make_data_qmod:
  update_qmain: false
  update_equations: false
  ext_start: 2010.1
  ext_end: 2050.4
  save_output: true

make_qmod:
  reestimate: true
  save_eq: true
  discover_tsrange: false
  max_lag: 5
  force_tsrange: false
  est_start: 1990.1
  est_end: 2019.4
  save_output: true

sol_qmod:
  sim_start: 2020.1
  sim_end: 2029.1
  sim_iter_limit: 100
  sim_convergence: 0.00001
  save_output: true

plot_qsol:
  short: false
  annual: false
  tourplot: true
  jobonly: false
  ypjonly: false
  yonly: false
  load_curr_vint: true
  load_prev_vint: true
  load_history: true
  ranges:
    short:
      plot_start: 2019.1
      plot_end: 2033.4
      show_table: true
      tab_start: 2024.1
      tab_end: 2029.4
    long:
      plot_start: 1990.1
      plot_end: 2056.4
      show_table: false
      tab_start: 2023.3
      tab_end: 2033.4
  plot_width: 1500
  plot_height: 650
  yoy_growth: true
  save_output: true
  preview_html: true
