vintages:
  comp: 25Q1
  curr: dev

data_main:
  data_from_disk: false

combine_equations:
  equations_subset:
    - _eq.txt # this keeps all equations (or comment this and uncomment below)
    # - af                    
    # - ag                    
    # - cpi                   
    # - ct                    
    # - e_headline_identitites
    # - else                  
    # - fir                   
    # - gdp_r_res             
    # - gv                    
    # - gvfd                  
    # - gvml                  
    # - gvsl                  
    # - hc                    
    # - kp                    
    # - lf                    
    # - mn                    
    # - model                 
    # - nr                    
    # - ocup                  
    # - pafsgf_hon            
    # - pmkb                  
    # - pprm                  
    # - prm                   
    # - rates                 
    # - taxes                 
    # - trade                 
    # - trmsadj               
    # - tu                    
    # - vday_vadc             
    # - vexp                  
    # - vis                   
    # - visjp                 
    # - visres                
    # - visus                 
    # - vlos                  
    # - y_headline_identitites
    # - ymedc_hon   

make_model:
  reestimate: true

solve_model:
  simulation_start: 2020.1
  simulation_end: 2030.4

plot_forecast:
  short: true
  annual: false
  tourplot: true
  jobonly: false
  ypjonly: false
  yonly: false
  ranges:
    short:
      plot_start: 2015.4
      plot_end: 2030.4
      show_table: true
      tab_start: 2025.1
      tab_end: 2030.4
    long:
      plot_start: 1990.1
      plot_end: 2056.4
      show_table: false
      tab_start: 2023.3
      tab_end: 2033.4
  yoy_growth: true

select_model:
  yvar: L_TRMS_HON
  xvars:
    - OCUPP_HON
  deterministic:
    - IQ2
    - IQ3
    - IQ4
    - CONST
  keep_vars: # force to keep constant, perdictors or certain lags if levels are I(1)
    # - CONST
    - L_TRMS_HON
    - OCUPP_HON
    - L_TRMS_HON.1
    - OCUPP_HON.1
  max_lag: 4
  second_pass: true
  save_equation: true
  model_select_range:
    start: 1970.1
    end: 2018.4
  estimation_range:
    start: 1970.1
    end: 2018.4
  forecast_range:
    start: 2024.1
    end: 2045.4
  diagnostic_tests: # see ?gets::getsm() for details
    ar_ljung_box:
      lag: null
      pval: 0.025
    arch_ljung_box:
      lag: null
      pval: null
    t_pval: 0.05
