vintages:
  prev: "25Q1"
  curr: "25Q2"

paths:
  raw: "data/raw"
  processed: "data/processed"
  equations: "equations"
  extend_script: "inst/extfuns/extend_qmain_history.R"
  wrangl_script: "inst/extfuns/wrangle_data.R"
  impext_script: "inst/extfuns/import_existing_fcst.R"
  addfac_script: "inst/extfuns/add_qmod.R"
  output: "output"
  figures: "output/figures"
  toursol_plot_list: "inst/extfuns/toursol_plot_list.R"
  qsol_plot_list: "inst/extfuns/qsol_plot_list.R"

constants:
  bank_start: 1900.1
  bank_end: 2100.4

data_qmain:
  data_from_disk: true
  exp_id_q: 333
  extend_history: true
  indicators_file: indicators.RDS
  save_output: true

combine_equations:
  eq_subset:
    # - ocup
    # - prm
    # - pprm
    # - trms
    # - vday
    # - vexp
    # - vis
    # - vlos
    - qmod
  save_output: true

make_data_qmod:
  update_qmain: false
  update_equations: false
  ext_start: 2010.1
  ext_end: 2050.4
  save_output: true

make_qmod:
  reestimate: true
  save_eq: true
  discover_tsrange: true
  max_lag: 9
  force_tsrange: false
  est_start: 1990.1
  est_end: 2019.4
  save_output: true

sol_qmod:
  sim_start: 2020.1
  sim_end: 2026.1
  sim_iter_limit: 100
  sim_convergence: 0.00001
  save_output: true

plot_qsol:
  short: false
  annual: false
  tourplot: true
  jobonly: false
  ypjonly: false
  yonly: false
  load_curr_vint: true
  load_prev_vint: true
  load_history: true
  ranges:
    short:
      plot_start: 2019.1
      plot_end: 2033.4
      show_table: true
      tab_start: 2024.1
      tab_end: 2029.4
    long:
      plot_start: 1990.1
      plot_end: 2056.4
      show_table: false
      tab_start: 2023.3
      tab_end: 2033.4
  plot_width: 1500
  plot_height: 650
  yoy_growth: true
  save_output: true
  preview_html: true
